export const tutors = [
 {id:'emma',name:'Emma Wilson',initials:'EW',color:'#f3e6d9',subjects:['Math','Algebra I','Algebra II'],grades:'6–12',min:6,max:12,rate:45,tag:'Making math click',bio:'Patient, practical support that turns “I can’t” into “I get it.” Emma breaks big ideas into small, manageable steps.',photo:'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=faces',modes:['Online','In person']},
 {id:'marcus',name:'Marcus Chen',initials:'MC',color:'#e3ebdf',subjects:['Science','Math'],grades:'5–10',min:5,max:10,rate:40,tag:'A little curiosity goes a long way',bio:'Marcus connects science and math to everyday life, helping students ask questions and build lasting understanding.',photo:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=faces',modes:['Online','In person']},
 {id:'sophie',name:'Sophie Davis',initials:'SD',color:'#f4e3da',subjects:['Reading','Math'],grades:'K–5',min:0,max:5,rate:35,tag:'Small steps. Big confidence.',bio:'A warm, encouraging approach to early reading and elementary math, with plenty of room to learn at your child’s pace.',photo:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=faces',modes:['Online','In person']},
 {id:'james',name:'James Parker',initials:'JP',color:'#e3e7ef',subjects:['Science','Algebra I','Algebra II'],grades:'7–12',min:7,max:12,rate:50,tag:'Finding the why behind the answer',bio:'James helps students work through challenging concepts with clear explanations and a calm, collaborative approach.',photo:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=faces',modes:['Online']}
];
export type Tutor = typeof tutors[number];
export function slotsFor(id:string) { const base = new Date(); base.setUTCDate(base.getUTCDate()+1); return Array.from({length:6},(_,i)=>{ const d=new Date(base); d.setUTCDate(d.getUTCDate()+Math.floor(i/2)); d.setUTCHours(i%2?23:22,0,0,0);return {id:`${id}-${d.toISOString()}`,time:d.toISOString()}; }); }
export function slotLabel(time:string){return new Date(time).toLocaleString('en-US',{timeZone:'America/Los_Angeles',weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
