'use client';
import Link from 'next/link';
import {useEffect,useState,useRef} from 'react';
import {tutors,Tutor,slotsFor,slotLabel} from '@/lib/tutors';
import {track,identity,source} from '@/lib/analytics';
export default function Experience({listing=false}:{listing?:boolean}){
 const modalRef=useRef<HTMLElement>(null);

 const [subject,setSubject]=useState('All subjects'),[grade,setGrade]=useState('All grades'),[mode,setMode]=useState('Any format'),[selected,setSelected]=useState<Tutor|null>(null),[slot,setSlot]=useState(''),[booked,setBooked]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState<{id:string;notification:string}|null>(null);
 useEffect(()=>{if(!selected)return;const previous=document.activeElement as HTMLElement;const dialog=modalRef.current;const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,a[href]')||[]);focusable()[0]?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const nodes=focusable();const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',trap);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',trap);document.body.style.overflow=old;previous?.focus();};},[selected]);
 useEffect(()=>{track('page_viewed',{page:listing?'tutors':'home'});const refresh=()=>fetch('/api/bookings').then(r=>r.json()).then(d=>setBooked(d.booked)).catch(()=>setError('Availability could not load. Please refresh to try again.'));refresh();const timer=setInterval(refresh,15000);return()=>clearInterval(timer);},[listing]);
 useEffect(()=>{if(!selected)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy){setSelected(null);setSlot('');}};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey);},[selected,busy]);
 const matches=tutors.filter(t=>(subject==='All subjects'||t.subjects.includes(subject))&&(grade==='All grades'||(+grade>=t.min&&+grade<=t.max))&&(mode==='Any format'||t.modes.includes(mode)));
 function open(t:Tutor){setSelected(t);setSlot('');setError('');setConfirmation(null);track('tutor_viewed',{tutor_id:t.id});}
 function close(){if(slot&&!confirmation)track('booking_abandoned',{tutor_id:selected!.id});setSelected(null);setSlot('');}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,tutor:selected!.id,slot,visitor:identity(),source:source()})});const result=await r.json();if(!r.ok){if(r.status===409){setBooked(x=>[...x,slot]);setSlot('');}throw new Error(result.error);}setBooked(x=>[...x,slot]);setConfirmation(result);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 return <><header><Link className="brand" href="/"><span className="brand-icon">a<span>b</span>c</span>ABC <strong>Tutoring</strong><i>✳</i></Link><nav><Link className={listing?'active':''} href="/tutors">Our tutors</Link><Link href="/#how-it-works">How it works</Link><Link className="button small" href="/tutors">Find your tutor <span>↗</span></Link></nav></header>
 <main>{!listing&&<section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> BIG POSSIBILITIES START WITH A LITTLE SUPPORT</div><h1>More confidence.<br/>More <em>“I’ve got this.”</em></h1><p>Friendly, one-on-one tutoring that meets your child where they are. Let’s make learning feel good again.</p><Link href="#tutors" className="button">Find the right tutor <span>↗</span></Link><div className="hero-notes"><span>✓ &nbsp; Kindergarten–12th grade</span><span>✓ &nbsp; Online & in person</span></div></div><div className="hero-art"><div className="photo-wrap"><img src="https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1000&h=900&fit=crop" alt="A student working through a lesson in a notebook"/><span className="spark">✳</span></div><div className="floating-note"><span>✦</span><div>A little support.<br/><strong>A lot of possibility.</strong></div></div><div className="photo-caption">ONE STUDENT. ONE TUTOR. THEIR OWN PACE.</div></div></section>}
 {!listing&&<div className="subject-strip"><span>A helping hand in</span><strong>↗ &nbsp; Math & algebra</strong><b>✳</b><strong>⚗ &nbsp; Science</strong><b>✳</b><strong>▤ &nbsp; Reading</strong><span>For the big leaps and the little wins.</span></div>}
 <section id="tutors" className="tutor-section"><div className="section-top"><div><div className="eyebrow">GOOD PEOPLE. GREAT LEARNING PARTNERS.</div><h2>Meet their next <em>“aha!”</em> person.</h2><p>Different strengths. The same care for your child’s progress.</p></div><span className="handwritten">A good fit makes all the difference ↙</span></div><div className="filters"><label>Subject<select value={subject} onChange={e=>{setSubject(e.target.value);track('subject_searched',{subject:e.target.value});}}>{['All subjects','Math','Algebra I','Algebra II','Science','Reading'].map(s=><option key={s}>{s}</option>)}</select></label><label>Grade level<select value={grade} onChange={e=>setGrade(e.target.value)}><option>All grades</option>{Array.from({length:13},(_,i)=><option value={i} key={i}>{i===0?'Kindergarten':`Grade ${i}`}</option>)}</select></label><label>Session type<select value={mode} onChange={e=>setMode(e.target.value)}>{['Any format','Online','In person'].map(s=><option key={s}>{s}</option>)}</select></label><div className="results">{matches.length} tutors to get to know</div></div>
 <div className="tutor-grid">{matches.map(t=><article className="tutor-card" key={t.id}><button className="portrait" style={{background:t.color}} onClick={()=>open(t)} aria-label={`View ${t.name}`}><img src={t.photo} alt={`${t.name}, sample tutor portrait`}/><span className="format">{t.modes.length>1?'Online & in person':'Online'}</span></button><div className="card-content"><div className="name-row"><h3>{t.name}</h3><span>${t.rate}<small>/hr</small></span></div><p className="grades">Grades {t.grades}</p><div className="tags">{t.subjects.map(s=><span key={s}>{s}</span>)}</div><p className="tagline">{t.tag}</p><div className="availability"><span/> {slotsFor(t.id).some(s=>!booked.includes(s.id))?'Available this week':'Fully booked this week'}</div><button className="outline" onClick={()=>open(t)}>Meet {t.name.split(' ')[0]} & book <span>↗</span></button></div></article>)}</div>{matches.length===0&&<div className="empty"><h3>No tutors match just yet.</h3><p>Try a different subject, grade, or session format.</p><button className="outline" onClick={()=>{setSubject('All subjects');setGrade('All grades');setMode('Any format');}}>Clear filters</button></div>}<p className="sample-note">Meet our sample tutor team. Profiles, rates, and schedules are illustrative for this prototype.</p></section>
 <section id="how-it-works" className="how"><div><div className="eyebrow">LESS BACK-AND-FORTH. MORE LEARNING.</div><h2>A good start is<br/>just three steps away.</h2><p>No accounts. No payment at booking.<br/>Just the support your child needs.</p></div><div className="steps">{[['01','Find your person','Explore tutors by subject, grade, and the way your child learns.'],['02','Pick a time','Choose an available, one-hour session that fits your family.'],['03','We’ll take it from here','Book your session. Dana will follow up with the details and invoicing.']].map(([n,title,desc])=><div key={n}><span>{n}</span><section><h3>{title}</h3><p>{desc}</p></section></div>)}</div></section></main><footer><Link href="/" className="brand">ABC <strong>Tutoring</strong><i>✳</i></Link><p>A little support for a brighter learning journey.</p><Link href="/insights">Prototype insights ↗</Link><span>© {new Date().getFullYear()} ABC Tutoring</span></footer>
 {selected&&<div className="overlay"><section ref={modalRef} className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="close" onClick={close} disabled={busy} aria-label="Close booking">×</button>{confirmation?<div className="confirmation"><span className="success-icon">✓</span><div className="eyebrow">ONE GOOD STEP FORWARD</div><h2 id="modal-title">You’re booked!</h2><p>Your one-hour session with <strong>{selected.name}</strong> is reserved.</p><div className="confirmation-details">{slotLabel(slot.slice(selected.id.length+1))} Pacific<br/>${selected.rate} · No payment collected</div><p>{confirmation.notification==='sent'?'Dana has been notified and will follow up with the details.':'Prototype booking saved. Dana’s notification is in the local outbox; email delivery is not active.'}</p><small>Reference: {confirmation.id.slice(0,8)}</small><button className="button" onClick={close}>Back to our tutors ↗</button></div>:<><div className="modal-profile"><img src={selected.photo} alt={selected.name}/><div><div className="eyebrow">YOUR LEARNING PARTNER</div><h2 id="modal-title">{selected.name}</h2><p>Grades {selected.grades} · ${selected.rate}/hour</p></div></div><p>{selected.bio}</p><h3>1. Choose a time</h3><p className="muted">One-hour sessions · All times in Pacific Time</p><div className="slots">{slotsFor(selected.id).filter(s=>!booked.includes(s.id)).map(s=><button key={s.id} className={slot===s.id?'chosen':''} onClick={()=>{setSlot(s.id);track('booking_started',{tutor_id:selected.id});}}>{slotLabel(s.time)}</button>)}</div>{slotsFor(selected.id).every(s=>booked.includes(s.id))&&<p>No available sessions. Please choose another tutor.</p>}{slot&&<form onSubmit={submit}><h3>2. Tell us a little about your student</h3><div className="form-grid"><label>Parent’s name<input name="parent" autoComplete="name" required maxLength={149}/></label><label>Parent’s email<input name="email" type="email" autoComplete="email" required maxLength={149}/></label><label>Student’s first name<input name="student" required maxLength={149}/></label><label>Student’s grade<select name="grade" required>{Array.from({length:selected.max-selected.min+1},(_,i)=>i+selected.min).map(i=><option value={i} key={i}>{i===0?'Kindergarten':`Grade ${i}`}</option>)}</select></label><label>Subject<select name="subject">{selected.subjects.map(s=><option key={s}>{s}</option>)}</select></label><label>Session type<select name="mode">{selected.modes.map(s=><option key={s}>{s}</option>)}</select></label></div><p className="muted">Dana will arrange the meeting location or online link and handle invoicing separately.</p><button className="button full" disabled={busy}>{busy?'Reserving your session…':`Book session · $${selected.rate} ↗`}</button><p className="sample-note">Prototype: use sample details. No payment required.</p></form>}{error&&<p role="alert" className="error">{error}</p>}</>}</section></div>}</>;
}
