import Link from 'next/link';
import {db} from '@/lib/db';
import {tutors} from '@/lib/tutors';
export const dynamic='force-dynamic';
export default function Insights(){
 const events=db.prepare('SELECT event,visitor,properties FROM events').all();
 const count=(name:string)=>events.filter(e=>e.event===name).length;
 const visitors=new Set(events.filter(e=>e.event==='page_viewed').map(e=>e.visitor)).size;
 const completed=new Set(events.filter(e=>e.event==='booking_completed').map(e=>e.visitor)).size;
 const properties=events.map(e=>({event:String(e.event),visitor:String(e.visitor),p:JSON.parse(String(e.properties)) as Record<string,string>}));
 const groups=(event:string,key:string)=>{const totals:Record<string,number>={};properties.filter(e=>e.event===event).forEach(e=>{const k=e.p[key]||'Unknown';totals[k]=(totals[k]||0)+1;});return Object.entries(totals).sort((a,b)=>b[1]-a[1]);};
 return <main className="insights"><Link href="/">← Back to ABC Tutoring</Link><div className="eyebrow" style={{marginTop:40}}>PROTOTYPE · AGGREGATE ACTIVITY ONLY</div><h1>What’s helping families<br/>take the next step?</h1><p>{process.env.NEXT_PUBLIC_POSTHOG_KEY?'PostHog forwarding is configured. Verify delivery in your PostHog project.':'Local event collection is active. Add a PostHog project key to enable live forwarding.'}</p><table><tbody><tr><th>Visitors to the site</th><td>{visitors}</td></tr><tr><th>Tutor profile views</th><td>{count('tutor_viewed')}</td></tr><tr><th>Booking starts (slot selections)</th><td>{count('booking_started')}</td></tr><tr><th>Completed bookings</th><td>{count('booking_completed')}</td></tr><tr><th>Visitors who booked</th><td>{visitors?Math.round(completed/visitors*100):0}%</td></tr></tbody></table><p>Counts reflect this local prototype, including test traffic. A visitor is one browser session. Booking completion is recorded by the server only after a successful reservation.</p>{[['Most-viewed tutors','tutor_viewed','tutor_id'],['Subjects parents explore','subject_searched','subject'],['Where visitors come from','page_viewed','source']].map(([title,event,key])=><section key={title}><h2>{title}</h2><table><tbody>{groups(event,key).map(([name,n])=><tr key={name}><td>{key==='tutor_id'?tutors.find(t=>t.id===name)?.name||name:name}</td><td>{n}</td></tr>)}</tbody></table>{groups(event,key).length===0&&<p>No activity yet. Browse a tutor or select a subject to see it here.</p>}</section>)}<h2>Notification outbox</h2><p>No personal details are displayed here.</p><table><tbody>{db.prepare('SELECT notification, COUNT(*) AS count FROM bookings GROUP BY notification').all().map(r=><tr key={String(r.notification)}><td>{String(r.notification)}</td><td>{String(r.count)}</td></tr>)}</tbody></table><p>Queued notifications are saved locally, not emailed. Configure the email service before accepting real bookings. This prototype insights page is public; add owner authentication before launch.</p></main>
}
